# Generated by Django 3.0.5 on 2020-04-08 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import patient.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('owner', models.CharField(default='some', max_length=150)),
                ('national_id', models.IntegerField(default=1)),
                ('id_num', models.IntegerField(default=1)),
                ('date_visited', models.DateTimeField(auto_now=True)),
                ('age', models.FloatField(default=1.1)),
                ('weight', models.FloatField(default=1.1)),
                ('sex', models.BooleanField(default=True)),
                ('blood_type', models.CharField(default='some', max_length=5)),
                ('previous_test_results', models.TextField(default='some')),
                ('prescription', models.TextField(default='some')),
                ('hospital', models.CharField(default='some', max_length=150)),
                ('imaging_center', models.CharField(default='some', max_length=150)),
                ('document', models.FileField(default='/test.jpg', upload_to=patient.models.document_location)),
                ('annotations', models.CharField(default='    ', max_length=500)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
