# Generated by Django 3.0.5 on 2020-04-14 23:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20200408_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='x',
        ),
        migrations.RemoveField(
            model_name='point',
            name='y',
        ),
        migrations.AddField(
            model_name='point',
            name='point',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
